"""update booking model

Revision ID: 59e34d47de43
Revises: c3221f6a6e5f
Create Date: 2026-09-16 16:27:58.254970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59e34d47de43'
down_revision: Union[str, Sequence[str], None] = 'c3221f6a6e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_query_logs_id'), table_name='agent_query_logs')
    op.drop_table('agent_query_logs')
    op.add_column('Booking_Details', sa.Column('movie_name', sa.String(), nullable=True))
    op.add_column('Booking_Details', sa.Column('language', sa.String(), nullable=True))
    op.create_index(op.f('ix_Booking_Details_movie_name'), 'Booking_Details', ['movie_name'], unique=False)
    op.drop_constraint(op.f('Booking_Details_movie_id_fkey'), 'Booking_Details', type_='foreignkey')
    op.drop_column('Booking_Details', 'movie_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Booking_Details', sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('Booking_Details_movie_id_fkey'), 'Booking_Details', 'Movie_Details', ['movie_id'], ['id'])
    op.drop_index(op.f('ix_Booking_Details_movie_name'), table_name='Booking_Details')
    op.drop_column('Booking_Details', 'language')
    op.drop_column('Booking_Details', 'movie_name')
    op.create_table('agent_query_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tool_used', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_query_logs_pkey'))
    )
    op.create_index(op.f('ix_agent_query_logs_id'), 'agent_query_logs', ['id'], unique=False)
    # ### end Alembic commands ###
