"""initial migration

Revision ID: c3221f6a6e5f
Revises: 
Create Date: 2026-09-09 17:24:55.263094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3221f6a6e5f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Movie_Details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Movie_name', sa.String(), nullable=True),
    sa.Column('Theatre_name', sa.String(), nullable=True),
    sa.Column('Ticket_price', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('total_seats', sa.Integer(), nullable=True),
    sa.Column('available_seats', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Movie_Details_Movie_name'), 'Movie_Details', ['Movie_name'], unique=False)
    op.create_index(op.f('ix_Movie_Details_Theatre_name'), 'Movie_Details', ['Theatre_name'], unique=False)
    op.create_index(op.f('ix_Movie_Details_Ticket_price'), 'Movie_Details', ['Ticket_price'], unique=False)
    op.create_index(op.f('ix_Movie_Details_description'), 'Movie_Details', ['description'], unique=False)
    op.create_index(op.f('ix_Movie_Details_id'), 'Movie_Details', ['id'], unique=False)
    op.create_index(op.f('ix_Movie_Details_language'), 'Movie_Details', ['language'], unique=False)
    op.create_table('Booking_Details',
    sa.Column('booking_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('seats_to_book', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['Movie_Details.id'], ),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.create_index(op.f('ix_Booking_Details_booking_id'), 'Booking_Details', ['booking_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Booking_Details_booking_id'), table_name='Booking_Details')
    op.drop_table('Booking_Details')
    op.drop_index(op.f('ix_Movie_Details_language'), table_name='Movie_Details')
    op.drop_index(op.f('ix_Movie_Details_id'), table_name='Movie_Details')
    op.drop_index(op.f('ix_Movie_Details_description'), table_name='Movie_Details')
    op.drop_index(op.f('ix_Movie_Details_Ticket_price'), table_name='Movie_Details')
    op.drop_index(op.f('ix_Movie_Details_Theatre_name'), table_name='Movie_Details')
    op.drop_index(op.f('ix_Movie_Details_Movie_name'), table_name='Movie_Details')
    op.drop_table('Movie_Details')
    # ### end Alembic commands ###
